version: "3"

services:
  postgres:
    image: postgres:17
    container_name: dev_database_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD no arquivo .env}
      POSTGRES_DB: ${POSTGRES_DB:-lms}
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
